"""Build-013 Dynamic Specification Engine

Revision ID: 0cad7138d674
Revises: 1357e1667415
Create Date: 2026-08-04 17:51:19.625814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cad7138d674'
down_revision: Union[str, Sequence[str], None] = '1357e1667415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('formula_code', sa.String(length=100), nullable=False),
    sa.Column('formula_name_en', sa.String(length=200), nullable=False),
    sa.Column('formula_name_bn', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula_type', sa.String(length=100), nullable=False),
    sa.Column('formula_expression', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_code')
    )
    op.create_index(op.f('ix_formula_rules_id'), 'formula_rules', ['id'], unique=False)
    op.create_table('specification_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_audits_id'), 'specification_audits', ['id'], unique=False)
    op.create_table('template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_versions_id'), 'template_versions', ['id'], unique=False)
    op.create_table('specification_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(length=100), nullable=False),
    sa.Column('field_name_en', sa.String(length=200), nullable=False),
    sa.Column('field_name_bn', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('input_control', sa.String(length=50), nullable=False),
    sa.Column('placeholder_en', sa.String(length=200), nullable=True),
    sa.Column('placeholder_bn', sa.String(length=200), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('is_system_field', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('minimum_value', sa.String(length=100), nullable=True),
    sa.Column('maximum_value', sa.String(length=100), nullable=True),
    sa.Column('minimum_length', sa.Integer(), nullable=True),
    sa.Column('maximum_length', sa.Integer(), nullable=True),
    sa.Column('regex_pattern', sa.Text(), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('formula_reference', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['specification_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_code')
    )
    op.create_index(op.f('ix_specification_fields_id'), 'specification_fields', ['id'], unique=False)
    op.create_table('field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('option_code', sa.String(length=100), nullable=False),
    sa.Column('option_name_en', sa.String(length=200), nullable=False),
    sa.Column('option_name_bn', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('option_value', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['specification_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_options_id'), 'field_options', ['id'], unique=False)
    op.create_table('specification_dependency_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('source_field_id', sa.Integer(), nullable=False),
    sa.Column('trigger_value', sa.String(length=255), nullable=False),
    sa.Column('target_field_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_field_id'], ['specification_fields.id'], ),
    sa.ForeignKeyConstraint(['target_field_id'], ['specification_fields.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_dependency_rules_id'), 'specification_dependency_rules', ['id'], unique=False)
    op.create_table('template_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('is_readonly', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('group_order', sa.Integer(), nullable=True),
    sa.Column('column_width', sa.Integer(), nullable=True),
    sa.Column('show_in_quotation', sa.Boolean(), nullable=True),
    sa.Column('show_in_job_order', sa.Boolean(), nullable=True),
    sa.Column('show_in_production', sa.Boolean(), nullable=True),
    sa.Column('show_in_invoice', sa.Boolean(), nullable=True),
    sa.Column('validation_override', sa.Text(), nullable=True),
    sa.Column('formula_override', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['specification_fields.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_field_mapping_id'), 'template_field_mapping', ['id'], unique=False)
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('minimum_value', sa.String(length=100), nullable=True),
    sa.Column('maximum_value', sa.String(length=100), nullable=True),
    sa.Column('regex_pattern', sa.Text(), nullable=True),
    sa.Column('validation_expression', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stop_processing', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['specification_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_template_field_mapping_id'), table_name='template_field_mapping')
    op.drop_table('template_field_mapping')
    op.drop_index(op.f('ix_specification_dependency_rules_id'), table_name='specification_dependency_rules')
    op.drop_table('specification_dependency_rules')
    op.drop_index(op.f('ix_field_options_id'), table_name='field_options')
    op.drop_table('field_options')
    op.drop_index(op.f('ix_specification_fields_id'), table_name='specification_fields')
    op.drop_table('specification_fields')
    op.drop_index(op.f('ix_template_versions_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_specification_audits_id'), table_name='specification_audits')
    op.drop_table('specification_audits')
    op.drop_index(op.f('ix_formula_rules_id'), table_name='formula_rules')
    op.drop_table('formula_rules')
    # ### end Alembic commands ###
