"""Create template field mapping table

Revision ID: 265c89eef6a4
Revises: 0cad7138d674
Create Date: 2026-08-05 00:08:39.187483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265c89eef6a4'
down_revision: Union[str, Sequence[str], None] = '0cad7138d674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('uq_template_field_mapping', 'template_field_mapping', ['template_id', 'field_id'])
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_constraint('uq_template_field_mapping', 'template_field_mapping', type_='unique')
    
    # ### end Alembic commands ###
