"""Create quotation master

Revision ID: 801c7d4b3911
Revises: 265c89eef6a4
Create Date: 2026-08-05 13:24:17.949712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c7d4b3911'
down_revision: Union[str, Sequence[str], None] = '265c89eef6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_no', sa.String(length=50), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_no')
    )
    op.create_index(op.f('ix_quotation_master_id'), 'quotation_master', ['id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_quotation_master_id'), table_name='quotation_master')
    op.drop_table('quotation_master')
    # ### end Alembic commands ###
