"""Create Party Management tables

Revision ID: 94e3402b6e12
Revises: 2b7f7070fb81
Create Date: 2026-07-17 00:50:07.605953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e3402b6e12'
down_revision: Union[str, Sequence[str], None] = '2b7f7070fb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=30), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_parties_mobile'), 'parties', ['mobile'], unique=False)
    op.create_index(op.f('ix_parties_party_name'), 'parties', ['party_name'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=30), nullable=False),
    sa.Column('customer_category', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('price_category', sa.String(length=100), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_customer_number'), 'customer_profiles', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_party_id'), 'customer_profiles', ['party_id'], unique=True)
    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.String(length=20), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_profiles_employee_number'), 'employee_profiles', ['employee_number'], unique=True)
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_party_id'), 'employee_profiles', ['party_id'], unique=True)
    op.create_table('party_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_contacts_id'), 'party_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_party_contacts_party_id'), 'party_contacts', ['party_id'], unique=False)
    op.create_table('party_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_number', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_roles_id'), 'party_roles', ['id'], unique=False)
    op.create_index(op.f('ix_party_roles_party_id'), 'party_roles', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_roles_role'), 'party_roles', ['role'], unique=False)
    op.create_index(op.f('ix_party_roles_role_number'), 'party_roles', ['role_number'], unique=True)
    op.create_table('supplier_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('supplier_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_category', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('preferred_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_profiles_id'), 'supplier_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_profiles_party_id'), 'supplier_profiles', ['party_id'], unique=True)
    op.create_index(op.f('ix_supplier_profiles_supplier_number'), 'supplier_profiles', ['supplier_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_profiles_supplier_number'), table_name='supplier_profiles')
    op.drop_index(op.f('ix_supplier_profiles_party_id'), table_name='supplier_profiles')
    op.drop_index(op.f('ix_supplier_profiles_id'), table_name='supplier_profiles')
    op.drop_table('supplier_profiles')
    op.drop_index(op.f('ix_party_roles_role_number'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_role'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_party_id'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_id'), table_name='party_roles')
    op.drop_table('party_roles')
    op.drop_index(op.f('ix_party_contacts_party_id'), table_name='party_contacts')
    op.drop_index(op.f('ix_party_contacts_id'), table_name='party_contacts')
    op.drop_table('party_contacts')
    op.drop_index(op.f('ix_employee_profiles_party_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_employee_number'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index(op.f('ix_customer_profiles_party_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_customer_number'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_parties_party_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_mobile'), table_name='parties')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
