"""Create Product Category Master

Revision ID: c4171da6af41
Revises: 6b26b57679d9
Create Date: 2026-07-30 01:13:30.681964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4171da6af41'
down_revision: Union[str, Sequence[str], None] = '6b26b57679d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_category_code'), 'product_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_product_categories_category_name'), 'product_categories', ['category_name'], unique=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_category_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_category_code'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
